<script type="text/javascript" src="https://www.google.com/jsapi?autoload=
{'modules':[{'name':'visualization','version':'1','packages':
['geomap']}]}"></script>

<div id="stats-menu">
    <a href="#map_world">Regional</a>
    <a href="#listenerstat_content">Listener Count</a>
</div>
<div id="listener-stats">
    <div class="stat">
        <h2><?php echo _("Regional Stats"); ?></h2>
        <div id="geolocation_date_range">
            <h3 style="padding-left: 0px">Date Range</h3>
            <input type="text" id="geo-stat-start-date-picker" class="input_text" />
            <input type="text" id="geo-stat-start-time-picker" class="input_text" />
            <input type="text" id="geo-stat-end-date-picker" class="input_text" />
            <input type="text" id="geo-stat-end-time-picker" class="input_text" />
            <div id="geo-stat-range-btn" class="btn btn-small" title="<?php echo _("Filter Stats")?>">
                <i class="icon-white icon-search"></i><span><?php echo _("Filter Stats")?></span>
            </div>
        </div>
        <a href="#" id="back-to-world-map-btn" style="display:none;">Back to world map</a>
        <div id="map_world"></div>
        <div id="map_country" style="display:none;"></div>
    </div>

    <div class="stat">
        <div id="listenerstat_content" class="alpha-block padded">
            <H2><?php echo _("Listeners")?></H2>
            <div id="flot_placeholder" style="height:300px;margin:0px 50px 0px 50px"></div>
            <div id="legend" style="width:600px;height:70px;margin:0px 50px 0px 50px"></div>
            <div id="date_form" style="float:left; margin:0px 0px">
                <h3 style="padding-left: 0px">Date Range</h3>
                <?php echo $this->date_form; ?>
            </div>
            <div id="errorStatus" style="float:right; width: 400px">
                <h3><?php echo _("Stream Data Collection Status")?></h3>
                <fieldset class="padded stream-setting-global">
                <?php foreach ($this->errorStatus as $k=>$v) {?>
                <div class='stream-status <?php echo ($v == 'OK')? 'status-good' : 'status-error' ?>'><p><?php echo $k?>: <?php echo $v?></p></div>
                <?php }?>
                </fieldset>
            </div>
            <div style="clear: both;"></div>
            <?php $bandwidthUsage = Application_Model_Preference::getBandwidthLimitCounter(); ?>
            <?php $bandwidthLimit = Application_Model_Preference::getBandwidthLimit(); ?>
            <?php $percentInUse = sprintf("%01.1f%% ", $bandwidthUsage/$bandwidthLimit*100); ?>
            <div id="bandwidth_usage">
                <div style="padding-bottom: 2px;"><?php echo _("Monthly Listener Bandwidth Usage") ?></div>
                <div class="bandwidth_usage_progress_bar"></div>
                <div class="bandwidth_usage_percent_in_use"><?php echo $percentInUse .  _("in use") ?></div>
                <div class="bandwidth_usage_used" style="width:<?php echo sprintf("%01.1f%%", min(100, $bandwidthUsage/$bandwidthLimit*100)) ?>;"></div>

                <div style="margin-top: 17px; font-size: 12px;"><?php echo sprintf("%01.1fGB of %01.1fGB", $bandwidthUsage/pow(2, 30), $bandwidthLimit/pow(2, 30)); ?></div>
            </div>
        </div>
    </div>

</div>
