<script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.3/d3.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/topojson/1.6.9/topojson.min.js"></script>
<script src="/js/libs/datamaps.world.js"></script>
<script src="/js/libs/country-code-mapping.json"></script>
<div id="container" style="width:100%; height:50%; padding-top: 0px !important; margin-top:0px !important;"></div>
<script>

    var map_data = {};
    $.get("/rest/listener-stats/geolocation", {start: '2015-01-01 00:00:00', end: '2015-12-31 00:00:00'}, function(data) {
        data = JSON.parse(data);
        $.each(data, function(k,v) {
            map_data[country_code_map[k]] = {};
            map_data[country_code_map[k]]["listeners"] = v.length;
            map_data[country_code_map[k]]["fillKey"] = 'MEDIUM';
        });
    console.log(map_data);

    });

    var map = new Datamap({
        element: document.getElementById('container'),
        responsive: true,
        fills: {
            HIGH: '#afafaf',
            LOW: '#123456',
            MEDIUM: 'blue',
            defaultFill: 'grey'
        },
        data: map_data,
        geographyConfig: {
            popupTemplate: function(geo, data) {
                if (data) {
                    return ['<div class="hoverinfo"><strong>',
                        geo.properties.name,
                        ': ' + data.listeners,
                        ' Listeners</strong></div>'].join('');
                } else {
                    return ['<div class="hoverinfo"><strong>',
                        geo.properties.name,
                        ': ' + 0,
                        ' Listeners</strong></div>'].join('');
                }

            }
        }
    });

    $(window).on('resize', function() {
        map.resize();
    });
</script>

<div id="listenerstat_content" class="alpha-block padded">
    <H2><?php echo _("Listeners")?></H2>
    <div id="flot_placeholder" style="height:300px;margin:0px 50px 0px 50px"></div>
    <div id="legend" style="width:600px;height:70px;margin:0px 50px 0px 50px"></div>
    <div id="date_form" style="float:left; margin:0px 0px">
        <h3 style="padding-left: 0px">Date Range</h3>
        <?php echo $this->date_form; ?>
    </div>
    <div id="errorStatus" style="float:right; width: 400px">
        <h3><?php echo _("Stream Data Collection Status")?></h3>
        <fieldset class="padded stream-setting-global">
        <?php foreach ($this->errorStatus as $k=>$v) {?>
        <div class='stream-status <?php echo ($v == 'OK')? 'status-good' : 'status-error' ?>'><p><?php echo $k?>: <?php echo $v?></p></div>
        <?php }?>
        </fieldset>
    </div>
    <div style="clear: both;"></div>
    <?php $bandwidthUsage = Application_Model_Preference::getBandwidthLimitCounter(); ?>
    <?php $bandwidthLimit = Application_Model_Preference::getBandwidthLimit(); ?>
    <?php $percentInUse = sprintf("%01.1f%% ", $bandwidthUsage/$bandwidthLimit*100); ?>
    <div id="bandwidth_usage">
        <div style="padding-bottom: 2px;"><?php echo _("Monthly Listener Bandwidth Usage") ?></div>
        <div class="bandwidth_usage_progress_bar"></div>
        <div class="bandwidth_usage_percent_in_use"><?php echo $percentInUse .  _("in use") ?></div>
        <div class="bandwidth_usage_used" style="width:<?php echo sprintf("%01.1f%%", min(100, $bandwidthUsage/$bandwidthLimit*100)) ?>;"></div>

        <div style="margin-top: 17px; font-size: 12px;"><?php echo sprintf("%01.1fGB of %01.1fGB", $bandwidthUsage/pow(2, 30), $bandwidthLimit/pow(2, 30)); ?></div>
    </div>
</div>
